Docs example name clash
Content negotiation example in extending flask restful won't work out of the box. json.dumps() will throw error AttributeError: 'function' object has no attribute 'dumps' as we've just defined a function with the same name